### ISSUE TITLE
Example models for testing purpose

### ISSUE THREAD

**Issue by kungfooman** [TheDushan/OpenWolf#3]
Hi, since there is support for MD5 and Unreal Models, which reference files we can test? E.g. Doom 3 models don't work I guess, because they have CPU-calculated weights often more than 4, and XReal GPU just supports up to 4.

Some little reference .pak with a level with each possible thing (models, physics) would be very helpful.

**Comment by TheDushan** [comment]
I will upload and continue with development :)
so because of that reason I will close this issue
