### ISSUE TITLE
CMake for bspc

### ISSUE THREAD

**Issue by wtfbbqhax** [TheDushan/OpenWolf#5]
Add Cmake for bspc

**Comment by TheDushan** [comment]
Fixed compiling on Windows platform :)

**Comment by TheDushan** [comment]
I will update and I will complete whole cMake system for the engine in next few days.

**Comment by wtfbbqhax** [comment]
You should setup continuous integration through github for at least the
windows builds.

**Comment by TheDushan** [comment]
Fixed compiling BSPC :)
